In [2]:
import numpy as np

In [3]:
def getMatrix(beta,omega,gamma,roh,psi,mu,I,S):
    m = [
    [-(beta*I)-mu-omega,-beta*S,+psi,0],
    [beta*I, (beta*S) - mu- gamma, 0 ,0],
    [omega, 0, -mu-psi-roh,0],
    [0, gamma, roh, -mu]
    ]
    return m 

In [4]:
alpha= 0.03             #Birth rate
beta = 0.03             #Infection per day
omega= 0.00020185       #Rate of first dose of vacination
gamma= 0.0476           #Recovered rate
roh=  1/4380            #Time between first and second dose
psi= 1/3650             #first dose wanes in immunity
mu= 0.000035342 
N = 1


I = 0
S = mu*N*(mu+psi+roh)/((mu+psi+roh)*(mu+omega)-omega*psi)

m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
e,_ = np.linalg.eig(m)
e

array([-3.53420000e-05, -1.08363068e-04, -6.66454037e-04, -3.97423725e-02])

In [5]:
alpha=  0.03            #Birth rate
beta = 0.03             #Infection per day
omega= 0.00020185       #Rate of first dose of vacination
gamma= 0.0476           #Recovered rate
roh=  1/4380            #Time between first and second dose
psi= 1/3650             #first dose wanes in immunity
mu= 0.000035342 
N = 1


I = (mu*N)/(mu+gamma)-((psi*omega)/(beta*(mu+psi+roh))) - (mu+omega)/beta
S = (mu+gamma)/beta

m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
e,_ = np.linalg.eig(m)
e

array([-3.53420000e-05,  3.93756105e-03, -3.85895685e-03, -5.35624819e-04])

In [7]:

beta = 0.261994381      #Infection per day
omega= 0.000471498      #Rate of first dose of vacination
gamma= 0.0476           #Recovered rate
roh=  1/4380            #Time between first and second dose
psi= 1/3650             #first dose wanes in immunity
mu= 0.000035342 
N = 1


I = 0
S = mu*N*(mu+psi+roh)/((mu+psi+roh)*(mu+omega)-omega*psi)

m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
e,_ = np.linalg.eig(m)
e

array([-3.53420000e-05, -1.62490332e-04, -8.81974773e-04, -1.28994105e-02])

In [24]:
beta = 0.261994381      #Infection per day
omega= 0.000471498      #Rate of first dose of vacination
gamma= 0.0476           #Recovered rate
roh=  1/4380            #Time between first and second dose
psi= 1/3650             #first dose wanes in immunity
mu= 0.000035342 
N = 1

I = (mu*N)/(mu+gamma)-((psi*omega)/(beta*(mu+psi+roh))) - (mu+omega)/beta
S = (mu+gamma)/beta

m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
e,_ = np.linalg.eig(m)
e



array([-3.53420000e-05,  5.16562791e-03, -5.12239053e-03, -5.34969113e-04])

In [25]:
# beta = 0.261994381      #Infection per day
# omega= 0.00020185      #Rate of first dose of vacination
# gamma= 0.0476           #Recovered rate
# roh=  1/4380            #Time between first and second dose
# psi= 1/3650             #first dose wanes in immunity
# mu= 0.000035342 
# N = 1

# I = 0
# S = mu*N*(mu+psi+roh)/((mu+psi+roh)*(mu+omega)-omega*psi)

# m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
# e,_ = np.linalg.eig(m)
# e

array([-3.53420000e-05, -1.08363068e-04, -6.66454037e-04,  2.12951130e-02])

In [26]:
# beta = 0.261994381      #Infection per day
# omega= 0.00020185      #Rate of first dose of vacination
# gamma= 0.0476           #Recovered rate
# roh=  1/4380            #Time between first and second dose
# psi= 1/3650             #first dose wanes in immunity
# mu= 0.000035342 
# N = 1

# I = (mu*N)/(mu+gamma)-((psi*omega)/(beta*(mu+psi+roh))) - (mu+omega)/beta
# S = (mu+gamma)/beta

# m = np.matrix(getMatrix(beta,omega,gamma,roh,psi,mu,I,S))
# e,_ = np.linalg.eig(m)
e

array([-3.53420000e-05,  2.59755505e-03, -2.69347253e-03, -5.33226298e-04])